apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: argocd
  description: |
    Backstage is an open-source developer portal that puts the developer experience first.
  links:
    - title: Website
      url: https://argocd.liquid-reply.net/
  annotations:
    github.com/project-slug: argo/argo-cd
    backstage.io/techdocs-ref: dir:.
    lighthouse.com/website-url: https://argocd.liquid-reply.net/
spec:
  type: library
  owner: user:default/guest
  lifecycle: experimental